import { assertDeviceModel } from "../model/deviceModel.js";
import { variationName } from "../model/modelSettings.js";
import { writeCmos } from "./cmosWriter.js";
import { writeThyristor } from "./thyristorWriter.js";

const defaults = {
  Diode: { IS: "1e-14", N: "1", RS: "0.1" },
  BJT: { IS: "1e-14", BF: "100", VAF: "100" },
  MOSFET: { VTO: "2", KP: "1", LAMBDA: "0.01", RD: "10m", RS: "10m" }
};

function paramsText(params) {
  return Object.entries(params).filter(([, value]) => value !== "" && value != null)
    .map(([key, value]) => `${key.toUpperCase()}=${value}`).join(" ");
}

export function writeModel(model) {
  assertDeviceModel(model);
  const p = { ...(defaults[model.deviceType] || {}), ...model.spiceParameters };
  const variation = model.variation;
  const kName = variationName(model);
  if (variation?.target && !["PhotoCoupler-CMOS", "Thyristor", "Triac"].includes(model.deviceType)) {
    const key = variation.target;
    const value = p[key] ?? (key === "BF" ? "100" : "1");
    p[key] = `{(${String(value).replace(/^\{(.*)\}$/, "$1")})*${kName}}`;
  }
  const comments = String(model.comment || "").split(/\r\n|\r|\n/).map(line => `* ${line}`).join("\n");
  const header = `${comments}\n* ${model.deviceName} - generated by LTspice Model Package Generator\n* Tnom=${model.temperature} degC${variation?.target ? `\n* Variation target: ${variation.target}\n.param ${kName}=${variation.k}` : ""}`;
  if (model.deviceType === "PhotoCoupler-CMOS" && !model.externalModel) return `${header}\n${writeCmos(model)}`;
  if (["Thyristor", "Triac"].includes(model.deviceType)) return `${header}\n${writeThyristor(model)}`;
  if (model.modelType === "MODEL") {
    return `${header}\n.model ${model.deviceName} ${model.polarity}(${paramsText(p)})\n`;
  }
  const ports = model.pins.map(pin => pin.name).join(" ");
  if (["PhotoMOS-Relay", "PhotoCoupler-CMOS"].includes(model.deviceType)) {
    const external = model.externalModel;
    if (!external?.libraryPath || /[\r\n"\x00]/.test(external.libraryPath)) throw new Error("外部ライブラリのパスを指定してください（改行・引用符は使用できません）。");
    if (!/^[A-Za-z0-9_.-]+$/.test(external.subcircuit || "")) throw new Error("元モデルの.SUBCKT名を指定してください。");
    if (external.subcircuit.toLowerCase() === model.deviceName.toLowerCase()) throw new Error("Device nameは元の.SUBCKT名と異なる名前にしてください（例: MY_G3VM）。");
    const expectedPins = model.pins.map(pin => pin.name);
    const order = external.pinOrder;
    if (!Array.isArray(order) || order.length !== expectedPins.length || new Set(order).size !== expectedPins.length || order.some(pin => !expectedPins.includes(pin))) throw new Error(`元モデルの端子順には ${expectedPins.join(" ")} を1回ずつ指定してください。`);
    return `${header}\n* Original vendor library is an external dependency.\n.include "${external.libraryPath}"\n.SUBCKT ${model.deviceName} ${ports}\nXCORE ${order.join(" ")} ${external.subcircuit}\n.ENDS ${model.deviceName}\n`;
  }
  if (model.deviceType === "MOSFET") {
    const internal = `${model.deviceName}__CORE`;
    return `${header}\n.SUBCKT ${model.deviceName} ${ports}\nM1 D G S S ${internal}\n.model ${internal} ${model.polarity}(${paramsText(p)})\n.ENDS ${model.deviceName}\n`;
  }
  const ctr = String(p.CTR ?? "1").replace(/^\{(.*)\}$/, "$1");
  const ctrCurve=model.characteristicCurves.find(curve=>curve.name==="IF-CTR");
  const baseCtrExpression=ctrCurve?.points?.length
    ? `(table(max(I(DLED),0), ${ctrCurve.points.slice().sort((a,b)=>a.IF-b.IF).map(point=>`${point.IF},${point.CTR}`).join(", ")}))${variation?.target === "CTR" ? `*${kName}` : ""}`
    : ctr;
  const ctrExpression = p.CTRTC
    ? `(${baseCtrExpression}+${p.CTRTC}*(temp-${p.TNOM ?? model.temperature}))`
    : baseCtrExpression;
  const diode = paramsText({ IS: p.IS ?? "1e-14", N: p.N ?? "1.5", RS: p.RS ?? "1" });
  const outputCapacitance = p.CCE ? `\nCCE C E ${p.CCE}` : "";
  return `${header}\n.SUBCKT ${model.deviceName} ${ports}\nDLED A K ${model.deviceName}__LED\nBPHOTO C E I={${ctrExpression}*max(I(DLED),0)}\nRCE C E 1G${outputCapacitance}\n.model ${model.deviceName}__LED D(${diode})\n.ENDS ${model.deviceName}\n`;
}
