import { assertDeviceModel } from "../model/deviceModel.js";

const defaults = {
  Diode: { IS: "1e-14", N: "1", RS: "0.1", CJO: "10p", TT: "10n" },
  BJT: { IS: "1e-14", BF: "100", VAF: "100", CJE: "10p", CJC: "5p", TF: "1n" },
  MOSFET: { VTO: "2", KP: "1", LAMBDA: "0.01", RD: "10m", RS: "10m", CGS: "100p", CGD: "50p" }
};

function paramsText(params) {
  return Object.entries(params).filter(([, value]) => value !== "" && value != null)
    .map(([key, value]) => `${key.toUpperCase()}=${value}`).join(" ");
}

export function writeModel(model) {
  assertDeviceModel(model);
  const p = { ...(defaults[model.deviceType] || {}), ...model.spiceParameters };
  const header = `* ${model.deviceName} - generated by LTspice Model Package Generator\n* Tnom=${model.temperature} degC`;
  if (model.modelType === "MODEL") {
    return `${header}\n.model ${model.deviceName} ${model.polarity}(${paramsText(p)})\n`;
  }
  const ports = model.pins.map(pin => pin.name).join(" ");
  if (model.deviceType === "MOSFET") {
    const internal = `${model.deviceName}__CORE`;
    return `${header}\n.SUBCKT ${model.deviceName} ${ports}\nM1 D G S S ${internal}\n.model ${internal} ${model.polarity}(${paramsText(p)})\n.ENDS ${model.deviceName}\n`;
  }
  const ctr = p.CTR ?? "1";
  const ctrCurve=model.characteristicCurves.find(curve=>curve.name==="IF-CTR");
  const ctrExpression=ctrCurve?.points?.length
    ? `table(max(I(DLED),0), ${ctrCurve.points.slice().sort((a,b)=>a.IF-b.IF).map(point=>`${point.IF},${point.CTR}`).join(", ")})`
    : ctr;
  const diode = paramsText({ IS: p.IS ?? "1e-14", N: p.N ?? "1.5", RS: p.RS ?? "1", CJO: p.CJO ?? "10p" });
  return `${header}\n.SUBCKT ${model.deviceName} ${ports}\nDLED A K ${model.deviceName}__LED\nBPHOTO C E I={${ctrExpression}*max(I(DLED),0)}\nRCE C E 1G\nCCE C E ${p.CCE ?? "10p"}\n.model ${model.deviceName}__LED D(${diode})\n.ENDS ${model.deviceName}\n`;
}
